clip:
  visual_backbone: 'RN50'

shuffle: true

dataset_variant: "random_prompts"

optimizer_variant: "LBFGS"

training_opt:

  variation: "image_plus_text_weighted" # This determines the rule for combining the text and images
  prompt_set: "bestImageNet"
  proj_path: "/nethome/bdevnani3/flash1/long_tail_lang/imagenet_text2img_upsampled2_balanced_proj400.npy"

  batch_size: 512
  dataset: ImageNet_LT
  dataloader: "paired"

  feature_dim: 1024
  num_classes: 1000
  num_epochs: 300
  num_workers: 12
