clip:
  visual_backbone: 'RN50'

shuffle: true

dataset_variant: "Balanced_culp_text"

optimizer_variant: "LBFGS"

training_opt:

  variation: "text_only" # This determines the rule for combining the text and images
  prompt_set: "ImageNet"
  proj_path: "/nethome/bdevnani3/flash1/long_tail_lang/proj_matrices/cupl_l2_proj_mix.npy"

  batch_size: 512
  dataset: ImageNet_LT
  dataloader: "paired"

  feature_dim: 1024
  num_classes: 1000
  num_epochs: 300
  num_workers: 12
