coslr: false
endlr: 0.0

plateaulr: false

multisteplr: true
milestones: [75]
gamma: 0.5


criterions:
  PerformanceLoss:
    def_file: ./loss/MSELoss.py
    loss_params: {}
    optim_params: null
    weight: 1.0
last: false
model:
  clip:
    optim_params: {lr: 0.00001, momentum: 0.9, weight_decay: 0.0005}
    params: {visual_backbone: 'RN50'}
  proj:
    optim_params: {lr: 0.001, momentum: 0.9, weight_decay: 0.0005}
    params: {in_dim: 1024, out_dim: 1024}
shuffle: true

dataset_variant: "random_prompts"

dataset_prep_variant: "400_per_class"

optimizer_variant: "diffgrad"
optimizer_args: {history_size: 10, max_iter: 4, lr: 0.05}

train_variant: 0
training_opt:

  text_encoder_frozen: true
  image_encoder_frozen: true

  eval_type: "image"

  batch_size: 512
  dataset: ImageNet_LT
  dataloader: "paired"
  display_step: 5
  feature_dim: 1024
  num_classes: 1000
  num_epochs: 100
  num_workers: 12
  open_threshold: 0.1
  sampler: null

  
  scheduler_params: {gamma: 0.1, step_size: 10}