clip:
  visual_backbone: 'RN50'

shuffle: true

dataset_variant: "random_prompts"

optimizer_variant: "LBFGS"

training_opt:

  variation: "image_plus_text" # This determines the rule for combining the text and images
  lam: 0.9
  prompt_set: "bestImageNet"

  batch_size: 512
  dataset: ImageNet_LT
  dataloader: "paired"

  feature_dim: 1024
  num_classes: 1000
  num_epochs: 300
  num_workers: 12
